# NumPy

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,5,2,51,6942]],np.int32)

In [3]:
myarr

array([[   3,    5,    2,   51, 6942]])

In [4]:
myarr[0,2]

2

In [5]:
myarr.shape

(1, 5)

In [6]:
myarr.dtype

dtype('int32')

** Conversion from other python structure **

In [7]:
listarray = np.array([[9,8,0],[7,3,4],[1,2,3]])

In [8]:
listarray

array([[9, 8, 0],
       [7, 3, 4],
       [1, 2, 3]])

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [11]:
listarray.dtype

dtype('int32')

In [12]:
z=np.zeros(5)

In [13]:
z

array([0., 0., 0., 0., 0.])

In [14]:
r=np.arange(20)

In [15]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
lispace=np.linspace(1,5,100) 

In [17]:
lispace

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [18]:
ran=np.empty((2,2))

In [19]:
ran

array([[2.12199579e-314, 1.21590359e-311],
       [2.96439388e-321, 6.95272004e-310]])

In [20]:
ranLike=np.empty_like((2,2))

In [21]:
ranLike

array([         0, 1075052544])

In [22]:
ide=np.identity(5)

In [23]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
ar=np.arange(99)

In [25]:
ar=ar.reshape(11,9)

In [26]:
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [27]:
ar.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
ar.shape

(11, 9)

In [29]:
ar.sum(axis=0)

array([495, 506, 517, 528, 539, 550, 561, 572, 583])

In [30]:
ar.sum(axis=1)

array([ 36, 117, 198, 279, 360, 441, 522, 603, 684, 765, 846])

In [31]:
ar.T

array([[ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90],
       [ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91],
       [ 2, 11, 20, 29, 38, 47, 56, 65, 74, 83, 92],
       [ 3, 12, 21, 30, 39, 48, 57, 66, 75, 84, 93],
       [ 4, 13, 22, 31, 40, 49, 58, 67, 76, 85, 94],
       [ 5, 14, 23, 32, 41, 50, 59, 68, 77, 86, 95],
       [ 6, 15, 24, 33, 42, 51, 60, 69, 78, 87, 96],
       [ 7, 16, 25, 34, 43, 52, 61, 70, 79, 88, 97],
       [ 8, 17, 26, 35, 44, 53, 62, 71, 80, 89, 98]])

In [32]:
for item in ar.flat:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98


In [33]:
ar.ndim

2

In [34]:
ar.nbytes

396

In [41]:
a=np.array([3,52,72,7])

In [42]:
a.argmax()

2

In [43]:
a.argsort()

array([0, 3, 1, 2], dtype=int64)

In [44]:
a.argmax(axis=0)

2

In [45]:
np.where(a>9)

(array([1, 2], dtype=int64),)

In [46]:
type(a)

numpy.ndarray

In [47]:
type(np.where(a>9))

tuple

In [52]:
np.nonzero(a)

(array([0, 1, 3], dtype=int64),)

In [49]:
a[2]=0

In [50]:
a

array([ 3, 52,  0,  7])

In [53]:
import sys

In [54]:
arr=[2,5,6,3]

In [56]:
np_arr=np.array(arr)

In [58]:
sys.getsizeof(1)*len(arr)

112

In [59]:
np_arr.itemsize*np_arr.size

16

In [62]:
np_arr.tolist()

[2, 5, 6, 3]

In [3]:
import sklearn

In [4]:
print("hi")

hi


In [7]:
#This is a comment